Repository AY2122S1-CS2103T-W17-3/tp, pull requests merged in 2021-11, with the labels that each got.

#285 Change application state and command result handling
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditGroupCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupCommand.java
  src/main/java/seedu/address/logic/commands/GroupsCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/JoinGroupCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MarkAsDoneCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAsDoneCommandParser.java
  src/main/java/seedu/address/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/address/logic/state/ApplicationState.java
  src/main/java/seedu/address/logic/state/ApplicationStateType.java
  src/main/java/seedu/address/logic/state/GroupInformationState.java
  src/main/java/seedu/address/logic/state/HomeState.java
  src/main/java/seedu/address/logic/state/StoredDataApplicationState.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/GroupsCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: bug, priority.High

#302 Update Project Portfolio Page (Jay)
  docs/team/jayasting98.md
Labels: documentation, priority.High

#290 Add missing user guide entry of undo command
  docs/UserGuide.md
Labels: bug, documentation, priority.High

#300 Add tests for CommandResult
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, testing

#282 Fix edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: bug, priority.High

#321 Update UG
  docs/UserGuide.md
Labels: documentation

#322 Branch update ug
  docs/UserGuide.md
Labels: documentation

#323 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#309 Update tests for JsonAdaptedGroup
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/storage/JsonAdaptedGroupTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
  src/test/java/seedu/address/testutil/GroupUtil.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, testing

#311 Update tests for JsonAdaptedPerson
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High, testing

#313 Add tests for JsonAdaptedTask
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: priority.High, testing

#316 Update tests for storage ID
  src/main/java/seedu/address/storage/Id.java
  src/test/java/seedu/address/storage/IdTest.java
Labels: priority.High, testing

#319 Update hungkhoaitay.md
  docs/team/hungkhoaitay.md
Labels: documentation

#283 Fix bugs - joinG no error message for duplicate person - expand task's name to new line
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/JoinGroupCommand.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/resources/view/TaskCard.fxml
Labels: bug

#329 Fix Div blocks
  docs/UserGuide.md
Labels: documentation, priority.High

#328 Add test cases for undo command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditGroupCommand.java
  src/main/java/seedu/address/logic/commands/JoinGroupCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/JoinGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAsDoneCommandTest.java
  src/test/java/seedu/address/logic/commands/RemoveCommandTest.java
Labels: priority.High, testing

#330 Shifted Command Overview and added testing
  docs/UserGuide.md
  src/test/java/seedu/address/logic/parser/EditGroupCommandParserTest.java
Labels: documentation

#335 Update Developer Guide Storage component class diagram
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation, priority.High

#340 Update Developer Guide Logic component section
  docs/DeveloperGuide.md
  docs/diagrams/ApplicationStateClassDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClassDiagram.puml
  docs/images/ApplicationStateClassDiagram.png
  docs/images/CommandClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClassDiagram.png
  docs/images/ParserClasses.png
Labels: documentation, priority.High

#342 Dg
  docs/DeveloperGuide.md
  docs/diagrams/EditGroupCommandRefSequenceDiagram.puml
  docs/diagrams/EditGroupCommandSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/EditGroupCommandRefSequenceDiagram.png
  docs/images/EditGroupCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#320 UG Screenshots unified and Update DG UI's component diagram
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/user-guide/GroupInformationPanel.png
  docs/images/user-guide/HomePanel.png
  docs/images/user-guide/findAlexDavidResult.png
  docs/images/user-guide/findG_CS2103T_Mates_Result.png
Labels: documentation

#344 Update help message
  docs/images/user-guide/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#350 Update notations and test table images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/user-guide/GroupInformationPanel.png
  docs/images/user-guide/HomePanel.png
  docs/images/user-guide/macError.png
Labels: documentation

#353 Add table of contents links in every User Guide section
  docs/UserGuide.md
Labels: documentation, priority.High

#346 Update User Guide page block formatting
  docs/UserGuide.md
Labels: documentation, priority.High

#360 Update UI diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation

#359 Update ug sreenshots
  docs/UserGuide.md
  docs/images/user-guide/afterEdit3rdGroup.png
  docs/images/user-guide/afterMark2ndTaskDone.png
  docs/images/user-guide/afterShow1stGroup.png
  docs/images/user-guide/beforeEdit3rdGroup.png
  docs/images/user-guide/beforeMark2ndTaskDone.png
  docs/images/user-guide/beforeShow1stGroup.png
  docs/images/user-guide/secondGroupAfterJoinGCommand.png
  docs/images/user-guide/secondGroupInitially.png
  docs/images/user-guide/typeJoinGCommand.png
Labels: documentation

#361 Change font and fix hyperlink
  docs/UserGuide.md
Labels: documentation

#367 Update sequence diagram for delete command
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: documentation, priority.High

#362 Add implementation for AddTask and MarkAsDone
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTaskCommandActivityDiagram.puml
  docs/diagrams/AddTaskCommandSequenceDiagram.puml
  docs/diagrams/MarkAsDoneCommandActivityDiagram.puml
  docs/images/AddTaskCommandActivityDiagram.png
  docs/images/AddTaskCommandSequenceDiagram.png
  docs/images/MarkAsDoneCommandActivityDiagram.png
Labels: documentation

#358 Fix page block formatting
  docs/UserGuide.md
Labels: bug, documentation, priority.High

#372 Minor change in UI component
  docs/DeveloperGuide.md
Labels: documentation

#376 Javadoc ResultDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
Labels: documentation

#378 Update `MESSAGE_USAGE` for `addT` command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
Labels: enhancement

#373 Improve code Quality
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/JoinGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAsDoneCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
  src/main/java/seedu/address/logic/state/ApplicationState.java
  src/main/java/seedu/address/logic/state/GroupInformationState.java
  src/main/java/seedu/address/logic/state/HomeState.java
  src/main/java/seedu/address/logic/state/StoredDataApplicationState.java
Labels: documentation

#382 Fix add task command description
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
Labels: bug, priority.High

#379 Update adding panel and add rounded-corners UI to DG
  docs/DeveloperGuide.md
Labels: documentation

#384 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/JoinGroupActivityDiagram.puml
  docs/diagrams/JoinGroupRefSequenceDiagram.puml
  docs/images/JoinGroupActivityDiagram.png
  docs/images/JoinGroupRefSequenceDiagram.png
Labels: documentation

#383 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddTaskCommandActivityDiagram.puml
  docs/diagrams/MarkAsDoneCommandActivityDiagram.puml
  docs/images/AddTaskCommandActivityDiagram.png
  docs/images/MarkAsDoneCommandActivityDiagram.png
Labels: documentation

#380 Update Hung PPP
  docs/team/hungkhoaitay.md
Labels: documentation

#385 Ppp
  docs/team/asherhy.md
Labels: documentation

#394 Improve storage component code quality and add Javadoc comments
  src/main/java/seedu/address/ui/Card.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/Ui.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UiPart.java
Labels: priority.High

#389 Improve storage component code quality and add Javadoc comments
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/Id.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
Labels: priority.High

#395 Update UG
  docs/UserGuide.md
Labels: documentation

#397 Fix application state
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: bug, priority.High

#398 Update README.md
  README.md
Labels: documentation
